# Generated by Django 3.0.4 on 2020-03-12 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'body_style',
                'verbose_name_plural': 'body_styles',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'generation',
                'verbose_name_plural': 'generations',
            },
        ),
        migrations.CreateModel(
            name='Pony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('year', models.IntegerField(max_length=4)),
                ('hair_color', models.CharField(max_length=80)),
                ('body_color', models.CharField(max_length=80)),
                ('img_path', models.CharField(max_length=255)),
                ('body_style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyapp.BodyStyle', verbose_name='body_style')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyapp.Country', verbose_name='Country')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyapp.Generation', verbose_name='generation')),
            ],
            options={
                'verbose_name': 'pony',
                'verbose_name_plural': 'ponies',
            },
        ),
        migrations.CreateModel(
            name='UserPony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('details', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyapp.Condition', verbose_name='condition')),
                ('pony', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyapp.Pony', verbose_name='pony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'user_pony',
                'verbose_name_plural': 'user_ponies',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('user_pony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponyapp.UserPony', verbose_name='user_pony')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
    ]
