# Generated by Django 3.0.4 on 2020-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpony',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
